### ISSUE TITLE
there are both tabs and spaces in the source

### ISSUE THREAD

**Issue by xzackli** [simonsobs/xgpaint#1]
There are both tabs and spaces in the halos, i.e. see this line full of spaces:

https://github.com/simonsobs/xgpaint/blob/2ce3ce734e17cac42fedce22564bd219a5dbc92b/halo2fluxmap/halo2fluxmap/halos2map.py#L118

This is a bad because tabs are sometimes 4 spaces and sometimes 8, so I get some weird indentation when I open this file in my editor.

**Comment by msyriac** [comment]
Looks like an emacs-untabify is in order.
