### ISSUE TITLE
python 3

### ISSUE THREAD

**Issue by xzackli** [simonsobs/xgpaint#2]
Since we're in the python 2 sunset, would be good to make sure halo2fluxmap gives the same answers on 2 and 3.

**Comment by msyriac** [comment]
The best way to do that of course is to add unit tests and set up Travis. Bit of work, but worth it.

**Comment by marcelo-alvarez** [comment]
Is this a moot point now with the julia implementation? I.e. is there any reason to keep using the python version of halo2fluxmap?

**Comment by xzackli** [comment]
I think there's no point in upgrading to Python 3, but it's good to keep the Python 2 version around for a bit as a reference code. The julia code doesn't have certain features yet (manera HOD, Planck 2015 LF, scramble/shuffle).
